### ISSUE TITLE
Expose maas to external network for use on ubuntu headless server

### ISSUE THREAD

**Issue by longlostbro** [canonical/maas-multipass#5]
How can I modify maas.yml to allow access to maas from another machine on the network?

The machine I am installing this on is headless so I can't open the maas url in a browser.

**Comment by longlostbro** [comment]
One way is to connect is use an ssh tunnel.
https://serverfault.com/questions/1004529/access-an-http-server-as-localhost-from-an-external-pc-over-ssh

But I'm sure there is an easy way to do it by configuring the bridge correctly. Any tips or links would be helpful.

**Comment by antongisli** [comment]
you can achieve this using iptables rules on your host machine. I've covered it a bit in this guide:
https://github.com/antongisli/maas-baremetal-k8s-tutorial/blob/main/maas-setup.sh

specifically:
```
# Lastly, in order to be able to reach the service from outside our host machine,
# we can use port forwarding. Replace 10.10.10.5 with the IP seen on the ingress.
sudo iptables -t nat -A PREROUTING -p tcp -i $INTERFACE \
 --dport 8000 -j DNAT --to-destination 10.10.10.5:80
# if you want to persist this, run sudo dpkg-reconfigure iptables-persistent
# Now you should be able to open a browser and navigate to http://$IP_ADDRESS:8000
```

where $IP_ADDRESS is the IP address of your host that you should be able to reach via network. And $INTERFACE is the name of the physical network adapter device used by your host machine.

note you also need to replace `10.10.10.5` with the multipass VM IP address that you received.

someone else also wrote this:
https://maurow.bitbucket.io/notes/multipass-vm-port-forwarding.html

of course, you need to use the MAAS port instead of 8000->80, e.g. 5240->5240 should work:
`sudo iptables -t nat -A PREROUTING -p tcp -i $INTERFACE \
 --dport 5240 -j DNAT --to-destination 10.10.10.5:5240`

Also make sure you enable IPv4 forwarding:
```


First we need to allow IPv4 traffic forwarding on the host. Uncomment the line

net.ipv4.ip_forward=1

in /etc/sysctl.conf.

To reload this file run

$ sudo sysctl -p

Check that cat /proc/sys/net/ipv4/ip_forward returns 1.
```
